version: 2
jobs:
  # build with machine executor
  build:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build --stacktrace

  # release
  release:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew bintrayUpload

  # run the Python example
  py_example:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew processPyExample

workflows:
  version: 2
  build:
    jobs:
      - build

  # release with manual approval in CircleCI app
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release

  py_example:
    jobs:
      - py_example
