version: 2
jobs:
  # build with machine executor
  build:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build --stacktrace

  # release
  release:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew bintrayUpload

  # run the Python example
  py_example:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/py_example
    steps:
      - checkout
      - run:
          name: Activate environment
          command: python3 -m virtualenv env && source env/bin/activate
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Run processing
          command: python3 run_example.py

workflows:
  version: 2
  build:
    jobs:
      - build

  # release with manual approval in CircleCI app
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release

  py_example:
    jobs:
      - py_example
