version: 2
jobs:
  # build with machine executor
  build:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build --stacktrace

  # run python example in docker container
  python-example:
    docker:
      - image: circleci/python:3.7
    working_directory: ~
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker run -it --rm --name my-running-script -v "$PWD":/py_example -w /py_example python:3 python run_example.py

  # release
  release:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew bintrayUpload

workflows:
  version: 2
  build:
    jobs:
      - build
      - python-example:
          requires:
            - build

  # release with manual approval in CircleCI app
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release