version: 2
jobs:
  # build with machine executor
  build:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build

  # run python example in docker container
  python-example:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/py_example
    steps:
      - checkout
      - run: python3 run_example.py

  # release
  release:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew bintrayUpload


workflows:
  version: 2
  build:
    jobs:
      - build
      - python_example:
          requires:
            - build

  # release with manual approval in CircleCI app
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release